Make theme configurable in .env.example
phanbook/phanbook pull request #214
Opened 2016-12-26 00:40 UTC by arnoldbird

Support selecting a theme in .env.

2016-12-26 02:02 UTC, duythien commented
@arnoldbird Could you change the pull request to branch develop

2016-12-26 06:05 UTC, sergeyklay requested changes
Could you please change `tests/.env.travis` as well

2016-12-26 17:00 UTC, sergeyklay approved these changes

2016-12-27 00:43 UTC, merged

2016-12-27 00:43 UTC, duythien commented
Thanks @arnoldbird :)