Add and remove subscribe
phanbook/phanbook pull request #236
Opened 2017-03-18 05:54 UTC by duythien

2017-03-18 08:38 UTC, sergeyklay requested changes

2017-03-18 08:38 UTC, sergeyklay commented on core/modules/frontend/controllers/SubscribeController.php
> +            'unLink'  => $link . '/subscribe/remove?email=' . urlencode($this->crypt->encryptBase64(trim($email))),
is it possible to create these link by using Router an Url components?

2017-03-18 08:38 UTC, sergeyklay commented on core/modules/frontend/controllers/SubscribeController.php
> +                ? 'https://' : 'http://') . $this->request->getHttpHost();
I wold like to have some helper for this. we use this code in many places

2017-03-18 09:51 UTC, duythien commented on core/modules/frontend/controllers/SubscribeController.php
> +            'unLink'  => $link . '/subscribe/remove?email=' . urlencode($this->crypt->encryptBase64(trim($email))),
I think It can

2017-03-18 09:52 UTC, duythien commented on core/modules/frontend/controllers/SubscribeController.php
> +                ? 'https://' : 'http://') . $this->request->getHttpHost();
You mean add this line code to helper.php ?

2017-03-18 13:11 UTC, sergeyklay commented on core/modules/frontend/controllers/SubscribeController.php
> +                ? 'https://' : 'http://') . $this->request->getHttpHost();
for example, yes

2017-08-17 19:33 UTC, Ultimater commented
What's this PR waiting on?

2017-08-17 19:44 UTC, Ultimater commented on core/modules/frontend/controllers/SubscribeController.php
> +                ? 'https://' : 'http://') . $this->request->getHttpHost();
I like the idea of putting it somewhere else. What do you guys think of tossing such a link creator into `core/common/library/` so we have more control over it?

2017-08-17 20:36 UTC, sergeyklay commented on core/modules/frontend/controllers/SubscribeController.php
> +                ? 'https://' : 'http://') . $this->request->getHttpHost();
I agree

2017-08-17 20:36 UTC, sergeyklay commented
@Ultimater This PR should be separated to few things:

* Getting URIs by using Router an Url components
* Creating helper function for `https://` `http://` detection

2017-08-18 04:23 UTC, duythien commented
@Ultimater You can grab it. Currently I am very busy

2017-08-18 04:24 UTC, Ultimater commented
Mind assigning this?

2017-12-20 03:31 UTC, merged